### ISSUE TITLE
[QUESTION] How to retrieve more than 30 videos from a user 

### ISSUE THREAD

**Issue by emacollins** [Russell-Newton/TikTokPy#37]
**Ask your question**
I am pulling video data by passing through a username. The data that returns is what I want, however it only retrieves the user's 30 most recent videos. I see there is a video_limit parameter, but this seems to be invoked after the response is returned. I tried setting scrolling_down_time higher, but no matter how high, it still returns only 30 videos.  The data response gets saved to a json how I want it to, so the only issue is this 30 video limit. Any help would be appreciated, thanks!

Here is my function

```
def get_user_video_data(username: str) -> None:
   
    filepath = 'some/file/path'
    with TikTokAPI(scroll_down_time=100,navigation_retries=5, navigation_timeout=0, 
                   data_dump_file=filepath) as api:
        user = api.user(username)
```

**Comment by Russell-Newton** [comment]
Are you saying that there's only 30 videos in the data dump file? This is due to the nature of how TikTokPy retrieves videos. The first thing it does is grab the preloaded data that TikTok receives from its own API when you load a page. This is the data that gets dumped into the data dump file. If there's a scroll down time, TikTokPy will start scrolling down and capture the result of any API calls TikTok makes to retrieve more videos, comments, etc. Any of this extra data is saved under the "extras" field in the dumped JSON.

If you want to have access to the models.video.Video objects that are loaded on a user page, you can make use of the videos iterator from the loaded models.user.User

**Comment by emacollins** [comment]
Yes, only 30 videos in the data dump. Ideally I would want all videos from a user in the data dump file. The extras field in the data dump file seems to always be an empty list, even when setting a high scroll time. Will using the video iterator give me a way to get all of the videos then?

**Comment by emacollins** [comment]
It seems that iterating over the video objects still limits the results to 30 videos @Russell-Newton

**Comment by Russell-Newton** [comment]
The video iterator stops after the video limit is reached. This defaults to 25. Setting it to 0 will remove the limit. If it still only gets a handful of videos, it's possible then that something is keeping TikTok from retrieving more API data. If setting the video limit to 0 doesn't work, what version of TikTokPy are you using?

**Comment by emacollins** [comment]
Hmm okay, I set the limit to 0 with no luck. I am using version 0.1.9.post1

**Comment by Russell-Newton** [comment]
That'll do it. This was an issue that I fixed in 0.1.10.post1 if I remember correctly. I'd recommend updating to the latest version (0.1.11) and trying again.

**Comment by emacollins** [comment]
Awesome, I just updated and it seems my data dump files are much larger, so it seems to be capturing the extra data. Thank you so much!

**Comment by erdinhrmwn** [comment]
I'm using latest version but still get max 30 most recent videos even set video_limit to 0. Any clue for this?
